[tool.ruff]
line-length = 100
select = ["E", "F", "I"]
exclude = [
  ".venv",
  "alembic/versions",
]

[tool.ruff.isort]
known-first-party = ["app"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
exclude = [
  ".venv",
  "alembic/versions",
]
